### ISSUE TITLE
Improve example page

### ISSUE THREAD

**Issue by rafaelrinaldi** [rafaelrinaldi/data-components#2]
There's currently a silly  example page under the [`gh-pages`](https://github.com/rafaelrinaldi/data-components/tree/gh-pages) branch. It doesn't really show the potential of `data-components` though.

**Comment by rafaelrinaldi** [comment]
FYI I've added a brand new homepage with a simple shopping cart (a la todo list) application to show a possible use case for the library (hopefully). [Here it is](https://rafaelrinaldi.github.io/data-components).

Suggestions and improvements are always welcome :+1:

**Comment by gusaiani** [comment]
Looks pretty nice. A welcome addition.

**Comment by rafaelrinaldi** [comment]
@gusaiani Thanks! Hopefully this can show off potential use cases for the library :smile:
